apiVersion: v1
kind: Service
metadata:
  name: {{ include "bede-task.fullname" . }}
  {{- if .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  {{- else }}
  namespace: default
  {{- end }}
  labels:
    {{- include "bede-task.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8100
      protocol: TCP
      name: http
  selector:
    {{- include "bede-task.selectorLabels" . | nindent 4 }}